server:
  port: 80

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      #设置eureka server交互的地址服务和注册服务都需要的依赖
      #单机配置：defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7002/eureka

ribbon:
  # 建立连接所用的时间，适用于网络正常连接，两端连接时间
  ReadTimeout: 5000
  # 建立连接后从服务端读取到可用资源所需的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别打印哪个接口
    com.demo.springcloud.service.PaymentFeignService: debug
