server:
  port: 8401

spring:
  #服务别名，注册到nacos服务名称
  application:
    name: cloudalibaba-setinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111 #设置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080 # 设置sentinel地址
        port: 8719
        #增加持久化，放在sentinel重启，配置丢失
        datasource:
          ds1:
            nacos:
              server-addr: localhost:1111
              dataId: ${spring.application.name}
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow

#暴露点
management:
  endpoints:
    web:
      exposure:
        include: '*'

