server:
  port: 8601

spring:
  application:
    name: rocketmq-example
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          input1:
            consumer:
              orderly: true
          input2:
            consumer:
              orderly: false
              tags: tagStr

      bindings:
        output:
          destination: test-topic
          content-type: application/json
        input1:
          destination: test-topic
          content-type: text/plain
          group: test-group1
        input2:
          destination: test-topic
          content-type: text/plain
          group: test-group2
          consumer:
            concurrency: 20

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
