server:
  port: 9527

spring:
  #禁用缓存
  thymeleaf:
    cache: false
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh # 路由的ID，没有规定规则但要求唯一
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 提供者服务名称
          predicates:
            - Path=/payment/get/** # 断言，路径匹配的进行路由

        - id: payment_routh2 # 路由的ID，没有规定规则但要求唯一
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 提供者服务名称
          predicates:
            - Path=/payment/getPaymentlb/**  # 断言，路径匹配的进行路由
            #- After=2021-02-19T09:28:40.461+08:00[Asia/Shanghai]
            #- Cookie=username,EDZ

eureka:
  instance:
    hostname: gateway9527
  client:
    #true表示向注册中心注册自己
    register-with-eureka: true
    #是否从服务中心抓取已有的注册信息，默认true，单机无所谓，集群必须为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置eureka server交互的地址服务和注册服务都需要的依赖
      #单机配置
      defaultZone: http://localhost:7001/eureka
      #集群配置
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7002/eureka

