server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        enabled: true
        tx-service-group: my_tx_group
        enable-auto-data-source-proxy: true    #开启数据库代理
    nacos:
      discovery:
        server-addr: localhost:3344 #设置nacos地址
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: qiuroot889
    validationQuery: SELECT 1

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info